% Copyright (C) 1995,1996,1997,1998,1999,2000
%                       by Hiroshi Nakashima, Yasuki Saito and
%                          The Editorial Board of the IPSJ Journal
%
% ipsjpapers.cls 10-Jun-00 by Hiroshi Nakashima (ver 2.07)
% (revision history deleted)
% ipsjpapers.cls  1-Apr-96 by Hiroshi Nakashima (ver 2.00)

\ifx\pfmtname\undefined
\NeedsTeXFormat{LaTeX2e}
\else
\NeedsTeXFormat{pLaTeX2e}
\fi

\ProvidesClass{m-thesis}[2004/12/22 ver 1.01]
\input{sty/m-thesis.sty}
\endinput

